'use strict';

let mockCustomers = {};

let customers = [
  {"firstName":"Christina","lastName":"Tucker","email":"ctucker0@hp.com"},
  {"firstName":"Ashley","lastName":"Bell","email":"abell1@naver.com"},
  {"firstName":"Rachel","lastName":"Woods","email":"rwoods2@buzzfeed.com"},
  {"firstName":"Frank","lastName":"Wheeler","email":"fwheeler3@amazon.co.jp"},
  {"firstName":"Larry","lastName":"Gibson","email":"lgibson4@vinaora.com"},
  {"firstName":"Samuel","lastName":"Snyder","email":"ssnyder5@phoca.cz"},
  {"firstName":"Kathryn","lastName":"Nguyen","email":"knguyen6@drupal.org"},
  {"firstName":"Melissa","lastName":"Harvey","email":"mharvey7@posterous.com"},
  {"firstName":"Ashley","lastName":"Ellis","email":"aellis8@scribd.com"},
  {"firstName":"Wayne","lastName":"Tucker","email":"wtucker9@google.cn"},
  {"firstName":"Jennifer","lastName":"Richardson","email":"jrichardsona@google.com.br"},
  {"firstName":"Craig","lastName":"Rivera","email":"criverab@yahoo.com"},
  {"firstName":"Christopher","lastName":"Williams","email":"cwilliamsc@opera.com"},
  {"firstName":"Bruce","lastName":"Elliott","email":"belliottd@angelfire.com"},
  {"firstName":"Daniel","lastName":"Sims","email":"dsimse@jugem.jp"},
  {"firstName":"Matthew","lastName":"Gibson","email":"mgibsonf@nature.com"},
  {"firstName":"Jack","lastName":"Crawford","email":"jcrawfordg@engadget.com"},
  {"firstName":"Stephen","lastName":"Adams","email":"sadamsh@yellowbook.com"},
  {"firstName":"Donna","lastName":"King","email":"dkingi@so-net.ne.jp"},
  {"firstName":"Rachel","lastName":"Chapman","email":"rchapmanj@nytimes.com"},
  {"firstName":"Bobby","lastName":"Garza","email":"bgarzak@topsy.com"},
  {"firstName":"Linda","lastName":"Banks","email":"lbanksl@scientificamerican.com"},
  {"firstName":"Tina","lastName":"Bradley","email":"tbradleym@theatlantic.com"},
  {"firstName":"Martha","lastName":"Johnson","email":"mjohnsonn@dailymotion.com"},
  {"firstName":"Barbara","lastName":"Vasquez","email":"bvasquezo@wikipedia.org"},
  {"firstName":"Christina","lastName":"Turner","email":"cturnerp@ning.com"},
  {"firstName":"Harold","lastName":"Hart","email":"hhartq@netlog.com"},
  {"firstName":"Sharon","lastName":"Hernandez","email":"shernandezr@topsy.com"},
  {"firstName":"Catherine","lastName":"White","email":"cwhites@feedburner.com"},
  {"firstName":"Teresa","lastName":"Payne","email":"tpaynet@wufoo.com"},
  {"firstName":"Barbara","lastName":"Simpson","email":"bsimpsonu@tamu.edu"},
  {"firstName":"Bonnie","lastName":"Greene","email":"bgreenev@google.nl"},
  {"firstName":"Patrick","lastName":"Simpson","email":"psimpsonw@list-manage.com"},
  {"firstName":"Harold","lastName":"Lane","email":"hlanex@tinypic.com"},
  {"firstName":"Roger","lastName":"Reid","email":"rreidy@smugmug.com"},
  {"firstName":"Debra","lastName":"Brooks","email":"dbrooksz@state.tx.us"},
  {"firstName":"Jeffrey","lastName":"Watson","email":"jwatson10@ow.ly"},
  {"firstName":"Jane","lastName":"Oliver","email":"joliver11@redcross.org"},
  {"firstName":"Steven","lastName":"Wells","email":"swells12@archive.org"},
  {"firstName":"Bruce","lastName":"Martin","email":"bmartin13@usnews.com"},
  {"firstName":"Katherine","lastName":"Roberts","email":"kroberts14@is.gd"},
  {"firstName":"Robin","lastName":"Garrett","email":"rgarrett15@smugmug.com"},
  {"firstName":"Rachel","lastName":"Richardson","email":"rrichardson16@indiatimes.com"},
  {"firstName":"Joan","lastName":"West","email":"jwest17@biblegateway.com"},
  {"firstName":"Peter","lastName":"Johnston","email":"pjohnston18@smh.com.au"},
  {"firstName":"Nicole","lastName":"Harris","email":"nharris19@rediff.com"},
  {"firstName":"Eric","lastName":"Berry","email":"eberry1a@apache.org"},
  {"firstName":"Dennis","lastName":"Bradley","email":"dbradley1b@fastcompany.com"},
  {"firstName":"Phillip","lastName":"Harris","email":"pharris1c@com.com"},
  {"firstName":"Lori","lastName":"Daniels","email":"ldaniels1d@ezinearticles.com"},
  {"firstName":"Peter","lastName":"Nichols","email":"pnichols1e@globo.com"},
  {"firstName":"Sharon","lastName":"Owens","email":"sowens1f@trellian.com"},
  {"firstName":"Samuel","lastName":"Sullivan","email":"ssullivan1g@wunderground.com"},
  {"firstName":"Mildred","lastName":"Moreno","email":"mmoreno1h@cam.ac.uk"},
  {"firstName":"Laura","lastName":"Johnson","email":"ljohnson1i@wix.com"},
  {"firstName":"William","lastName":"Moore","email":"wmoore1j@marketwatch.com"},
  {"firstName":"Phillip","lastName":"Hansen","email":"phansen1k@dropbox.com"},
  {"firstName":"Lisa","lastName":"Phillips","email":"lphillips1l@cdc.gov"},
  {"firstName":"Matthew","lastName":"Tucker","email":"mtucker1m@discovery.com"},
  {"firstName":"Julia","lastName":"Gordon","email":"jgordon1n@smugmug.com"},
  {"firstName":"Barbara","lastName":"Rogers","email":"brogers1o@studiopress.com"},
  {"firstName":"Paula","lastName":"Green","email":"pgreen1p@arstechnica.com"},
  {"firstName":"Peter","lastName":"Harvey","email":"pharvey1q@issuu.com"},
  {"firstName":"Terry","lastName":"Graham","email":"tgraham1r@webnode.com"},
  {"firstName":"Russell","lastName":"Simpson","email":"rsimpson1s@accuweather.com"},
  {"firstName":"Margaret","lastName":"Roberts","email":"mroberts1t@economist.com"},
  {"firstName":"Terry","lastName":"Gordon","email":"tgordon1u@yellowbook.com"},
  {"firstName":"Cynthia","lastName":"Robertson","email":"crobertson1v@google.nl"},
  {"firstName":"Russell","lastName":"Murphy","email":"rmurphy1w@drupal.org"},
  {"firstName":"Albert","lastName":"Davis","email":"adavis1x@furl.net"},
  {"firstName":"Sara","lastName":"Hill","email":"shill1y@yelp.com"},
  {"firstName":"Richard","lastName":"Black","email":"rblack1z@networksolutions.com"},
  {"firstName":"Maria","lastName":"Smith","email":"msmith20@sohu.com"},
  {"firstName":"Benjamin","lastName":"King","email":"bking21@netvibes.com"},
  {"firstName":"Richard","lastName":"Howell","email":"rhowell22@tuttocitta.it"},
  {"firstName":"Gloria","lastName":"Lopez","email":"glopez23@prweb.com"},
  {"firstName":"Ernest","lastName":"Daniels","email":"edaniels24@amazon.com"},
  {"firstName":"Eugene","lastName":"Fields","email":"efields25@va.gov"},
  {"firstName":"Dennis","lastName":"Gonzales","email":"dgonzales26@craigslist.org"},
  {"firstName":"Nancy","lastName":"Gardner","email":"ngardner27@gravatar.com"},
  {"firstName":"Brian","lastName":"Sanchez","email":"bsanchez28@sun.com"},
  {"firstName":"Shawn","lastName":"Ortiz","email":"sortiz29@elpais.com"},
  {"firstName":"Howard","lastName":"Morales","email":"hmorales2a@ucoz.ru"},
  {"firstName":"Keith","lastName":"Warren","email":"kwarren2b@ed.gov"},
  {"firstName":"Rebecca","lastName":"Wheeler","email":"rwheeler2c@taobao.com"},
  {"firstName":"Andrew","lastName":"Nguyen","email":"anguyen2d@tripod.com"},
  {"firstName":"Paul","lastName":"Mendoza","email":"pmendoza2e@bizjournals.com"},
  {"firstName":"Janet","lastName":"Green","email":"jgreen2f@nationalgeographic.com"},
  {"firstName":"Jason","lastName":"Hayes","email":"jhayes2g@boston.com"},
  {"firstName":"Nicholas","lastName":"Carpenter","email":"ncarpenter2h@wiley.com"},
  {"firstName":"Mary","lastName":"Willis","email":"mwillis2i@google.co.uk"},
  {"firstName":"Jason","lastName":"Woods","email":"jwoods2j@cloudflare.com"},
  {"firstName":"Carl","lastName":"Carr","email":"ccarr2k@sina.com.cn"},
  {"firstName":"Cheryl","lastName":"Simpson","email":"csimpson2l@shutterfly.com"},
  {"firstName":"Ruby","lastName":"Richards","email":"rrichards2m@cam.ac.uk"},
  {"firstName":"Norma","lastName":"Brooks","email":"nbrooks2n@networksolutions.com"},
  {"firstName":"Terry","lastName":"Hansen","email":"thansen2o@epa.gov"},
  {"firstName":"Chris","lastName":"Wood","email":"cwood2p@i2i.jp"},
  {"firstName":"Michelle","lastName":"Burton","email":"mburton2q@soundcloud.com"},
  {"firstName":"Beverly","lastName":"Spencer","email":"bspencer2r@europa.eu"}
];

mockCustomers.getCustomer = function() {
  let x = Math.floor(Math.random() * 100);
  return customers[x];
};

mockCustomers.test = function() {
  return 'test';
};

module.exports = mockCustomers;
